/**
 * Canonical list of explicit gateway routes (excluding catch-all 404).
 * Keep in sync with app.ts route mounts and openapi paths.
 */
export const GATEWAY_ROUTE_MANIFEST = [
  { method: 'GET', path: '/health' },
  { method: 'POST', path: '/v1/session' },
  { method: 'POST', path: '/v1/session/refresh' },
  { method: 'POST', path: '/v1/quote' },
  { method: 'GET', path: '/v1/escrows/events' },
  { method: 'POST', path: '/v1/escrows' },
  { method: 'GET', path: '/v1/escrows/{id}' },
  { method: 'GET', path: '/v1/escrows/{id}/status' },
  { method: 'POST', path: '/v1/escrows/{id}/deposit' },
  { method: 'POST', path: '/v1/escrows/{id}/fiat-report' },
  { method: 'POST', path: '/v1/escrows/{id}/cancel' },
  { method: 'POST', path: '/v1/escrows/{id}/refund' },
  { method: 'POST', path: '/v1/escrows/{id}/disputes' },
  { method: 'POST', path: '/v1/escrows/{id}/disputes/{disputeId}/resolve' },
  { method: 'POST', path: '/v1/subscriptions' },
  { method: 'GET', path: '/v1/subscriptions' },
  { method: 'GET', path: '/v1/subscriptions/{id}' },
  { method: 'POST', path: '/v1/subscriptions/{id}/cancel' },
  { method: 'POST', path: '/v1/test/escrows/{id}/dispute' },
  { method: 'POST', path: '/v1/test/escrows/{id}/timeout' },
  { method: 'POST', path: '/v1/test/escrows/{id}/release' },
  { method: 'POST', path: '/v1/test/subscriptions/{id}/advance' },
  { method: 'POST', path: '/v1/test/subscriptions/{id}/fail-next' },
  { method: 'POST', path: '/v1/webhooks/inbound' },
  { method: 'GET', path: '/admin/keys' },
  { method: 'POST', path: '/admin/keys' },
  { method: 'POST', path: '/admin/keys/{id}/rotate' },
  { method: 'POST', path: '/admin/keys/{id}/cutover' },
  { method: 'POST', path: '/admin/keys/{id}/revoke' },
  { method: 'POST', path: '/admin/keys/{keyId}/merchants' },
  { method: 'GET', path: '/admin/keys/{keyId}/merchants' },
  { method: 'POST', path: '/admin/merchants/{id}/disable' },
  { method: 'GET', path: '/admin/merchants/{id}/risk/settings' },
  { method: 'PUT', path: '/admin/merchants/{id}/risk/settings' },
  { method: 'GET', path: '/admin/merchants/{id}/risk/lists' },
  { method: 'POST', path: '/admin/merchants/{id}/risk/lists' },
  { method: 'DELETE', path: '/admin/merchants/{id}/risk/lists/{entryId}' },
  { method: 'GET', path: '/admin/merchants/{id}/risk/decisions' },
  { method: 'POST', path: '/admin/merchants/{id}/periods/{periodKey}/close' },
  { method: 'POST', path: '/admin/merchants/{id}/ledger/corrections' },
  { method: 'POST', path: '/admin/merchants/{id}/periods/{periodKey}/payout-runs' },
  { method: 'GET', path: '/admin/payout-runs' },
  { method: 'GET', path: '/admin/payout-runs/{id}' },
  { method: 'GET', path: '/admin/merchants/{id}/periods/{periodKey}/statement.csv' },
  { method: 'GET', path: '/admin/webhooks' },
  { method: 'POST', path: '/admin/webhooks' },
  { method: 'GET', path: '/admin/webhooks/deliveries' },
  { method: 'GET', path: '/admin/webhooks/dlq' },
  { method: 'POST', path: '/admin/webhooks/deliveries/{id}/retry' },
  { method: 'GET', path: '/admin/webhooks/{id}' },
  { method: 'DELETE', path: '/admin/webhooks/{id}' },
  { method: 'POST', path: '/admin/webhooks/{id}/verify' },
  { method: 'POST', path: '/admin/webhooks/{id}/enable' },
  { method: 'POST', path: '/admin/webhooks/{id}/disable' },
] as const;

export type GatewayRouteManifestEntry = (typeof GATEWAY_ROUTE_MANIFEST)[number];
